name: Build and Release Custom JWT Generator

on:
  push:
    paths:
      - 'CustomGatewayJWTGenerator/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Check path
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in the directory:"
        ls -la

    - name: Build with Maven
      run: |
        cd CustomGatewayJWTGenerator
        mvn clean package

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_ACTION_PAT }}
      with:
        tag_name: jwt-gen-v${{ github.run_number }}
        release_name: Custom JWT Generator v${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: github.event_name == 'push'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_ACTION_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./CustomGatewayJWTGenerator/target/org.wso2.carbon.apimgt.custom.jwt.generator-1.0.0.jar
        asset_name: custom-jwt-generator.jar
        asset_content_type: application/java-archive